// biome-ignore-all lint: generated
// biome-ignore-all format: generated
/* eslint-disable */
/* prettier-ignore-start */
/*
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run apify actor generate-schema-types to regenerate this file.
 */

export interface Input {
  /**
   * List of Facebook group URLs to monitor
   *
   * @minItems 1
   */
  groupUrls: [string, ...string[]];
  /**
   * Email address to send notifications to (must match your Apify account email on free plan). At least one of recipientEmail or slackWebhookUrl is required.
   */
  recipientEmail?: string;
  /**
   * Slack incoming webhook URL to post notifications to. At least one of recipientEmail or slackWebhookUrl is required.
   */
  slackWebhookUrl?: string;
  /**
   * Posts containing any of these words (case-insensitive) will be skipped
   */
  ignoreKeywords: string[];
  /**
   * Use Apify residential proxies to avoid being blocked by Facebook
   */
  useResidentialProxy: boolean;
}
