// biome-ignore-all lint: generated
// biome-ignore-all format: generated
/* eslint-disable */
/* prettier-ignore-start */
/*
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run apify actor generate-schema-types to regenerate this file.
 */

export interface Output {
  /**
   * Posts found since the last run, one row per group with a new post
   */
  posts?: string;
}
